// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 设计规范 (设计规范)
class mlYLRsfXMPage extends StatelessWidget {
  const mlYLRsfXMPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 356,
                  top: 414,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFA989C5),
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '图标：#A989C5',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 356,
                  top: 130,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '按钮：#4C5773',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 356,
                  top: 272,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF7172AD),
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '重点色：#7172AD',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 768,
                  top: 272,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF949AAB),
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '文本：#949AAB',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 768,
                  top: 414,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF025478),
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '文本：#025478',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border.all(color: Color(0xFF949AAB), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '跨域身份管理系统\nSystem for Cross-domain Identity Management',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 768,
                  top: 130,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFEC808D),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '链接文本：EC808D',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFFFFFFF),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 11,
                  top: 272,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFEFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '背景：EFF1F3',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 11,
                  top: 414,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '文字背景：F7F8FA',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 11,
                  top: 130,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF4F5FA),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '背景色:  F4F5FA',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 768,
                  top: 556,
                  width: 300,
                  height: 100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF4F5FA),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '文本色：#4C5773',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 11,
                  top: 967,
                  width: 100,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 34,
                          top: 10.5,
                          width: 32,
                          height: 19,
                          child: Text(
                            '保存',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFF4C5773),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 191,
                  top: 967,
                  width: 100,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 34,
                          top: 10.5,
                          width: 32,
                          height: 19,
                          child: Text(
                            '取消',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 11,
                  top: 870,
                  width: 100,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 34,
                          top: 10.5,
                          width: 32,
                          height: 19,
                          child: Text(
                            '保存',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFFFFFFFF),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 191,
                  top: 870,
                  width: 100,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF949AAB), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 34,
                          top: 10.5,
                          width: 32,
                          height: 19,
                          child: Text(
                            '取消',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFF949AAB),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
