// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 邀请登录 (邀请登录)
class aZrZ6KCEAPage extends StatelessWidget {
  const aZrZ6KCEAPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 838,
                  top: 55,
                  width: 244,
                  height: 60,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 44,
                          top: 0,
                          width: 200,
                          height: 60,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 8,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'Xxxxxx ',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 20,
                                color: Color(0xFF4C5773),
                                height: 1,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 10,
                          width: 40,
                          height: 40,
                          child: CustomPaint(
                            size: Size(40, 40),
                            painter: _Path0Painter(),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 199,
                  width: 460,
                  height: 112,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 0,
                      right: 0,
                      top: 0,
                      bottom: 16,
                    ),
                    child: Text(
                      '接受您的邀请',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 24,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.8333,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 311,
                  width: 460,
                  height: 54,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '设置密码',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 365,
                  width: 460,
                  height: 48,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 12,
                      right: 6,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '密码(至少8位)',
                      textAlign: TextAlign.left,
                      style: TextStyle(fontSize: 14),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 413,
                  width: 460,
                  height: 54,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '确认密码',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 467,
                  width: 460,
                  height: 48,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 12,
                      right: 6,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '密码',
                      textAlign: TextAlign.left,
                      style: TextStyle(fontSize: 14),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
                Positioned(
                  left: 730,
                  top: 548,
                  width: 460,
                  height: 48,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(24),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 216,
                          top: 16,
                          width: 28,
                          height: 16,
                          child: Text(
                            '确定',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFFFFFFFF),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1161,
                  top: 381,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEB23, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1161,
                  top: 483,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEB17, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(20, 0);
    path.cubicTo(31.2, 0, 40, 8.8, 40, 20);
    path.cubicTo(40, 31.2, 31.2, 40, 20, 40);
    path.cubicTo(8.8, 40, 0, 31.2, 0, 20);
    path.cubicTo(0, 8.8, 8.8, 0, 20, 0);
    path.close();
    canvas.drawPath(path, Paint()..color = Color(0xFF949AAB));
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}
