// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 行政区划 (基础/地区/地区&国家/行政区划)
class P7dqVh7xyPage extends StatelessWidget {
  const P7dqVh7xyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 1602,
                  top: 281,
                  width: 126,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '坐标文件',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1475,
                  top: 281,
                  width: 126,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '电话区号',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1351,
                  top: 281,
                  width: 126,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '邮编',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1225,
                  top: 281,
                  width: 126,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '区域代码',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 65,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF7172AD),
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 10,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'XX管理后台',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 208,
                          top: 21,
                          width: 12,
                          height: 12,
                          child: Icon(
                            IconData(0xE8F1, fontFamily: 'lightIconFont'),
                            size: 12,
                            color: Color(0xFF777777),
                          ),
                        ),
                        Positioned(
                          left: 252,
                          top: 0,
                          width: 130,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 17,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE8B2, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFFFFFFFF),
                          ),
                        ),
                        Positioned(
                          left: 1789,
                          top: 11,
                          width: 100,
                          height: 44,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出管理',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 36,
                  top: 129,
                  width: 1692,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 129,
                  width: 32,
                  height: 587,
                  child: CustomPaint(
                    size: Size(32, 587),
                    painter: _Path0Painter(),
                  ),
                ),
                Positioned(
                  left: 36,
                  top: 137,
                  width: 300,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned.fill(
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 8,
                              right: 6,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '地区&国际 名称',
                              textAlign: TextAlign.left,
                              style: TextStyle(fontSize: 14),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 264,
                          top: 11,
                          width: 18,
                          height: 18,
                          child: Icon(
                            IconData(0xE8FF, fontFamily: 'lightIconFont'),
                            size: 18,
                            color: Color(0xFFAAAAAA),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 132,
                  top: 209,
                  width: 80,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 26,
                          top: 11.5,
                          width: 28,
                          height: 17,
                          child: Text(
                            '停用',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1765,
                  top: 129,
                  width: 120,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 44,
                          top: 18.5,
                          width: 32,
                          height: 19,
                          child: Text(
                            '添加',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFFFFFFFF),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 324,
                  top: 209,
                  width: 80,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 26,
                          top: 11.5,
                          width: 28,
                          height: 17,
                          child: Text(
                            '删除',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 228,
                  top: 209,
                  width: 80,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF797979), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 26,
                          top: 11.5,
                          width: 28,
                          height: 17,
                          child: Text(
                            '编辑',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1602,
                  top: 321,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '上传文件',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFFA989C5),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1475,
                  top: 321,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '--',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 36,
                  top: 281,
                  width: 40,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned.fill(
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border(
                                bottom: BorderSide(
                                  color: Color(0xFFF2F2F2),
                                  width: 1,
                                ),
                              ),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 12,
                          width: 23,
                          height: 16,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 2,
                                  width: 13,
                                  height: 13,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      color: Color(0xFFFFFFFF),
                                      borderRadius: BorderRadius.circular(0),
                                      border: Border.all(
                                        color: Color(0xFF777777),
                                        width: 1,
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 23,
                                  top: 0,
                                  width: 0,
                                  height: 16,
                                  child: Text(
                                    '',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF333333),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1475,
                  top: 391,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '020',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1225,
                  top: 321,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '156440000',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1225,
                  top: 391,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '156440100',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1351,
                  top: 321,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '--',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1351,
                  top: 391,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '510000',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1602,
                  top: 391,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '上传文件',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFFA989C5),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 90,
                  top: 321,
                  width: 446,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Guangdong Province',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 90,
                  top: 391,
                  width: 446,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Guangdong\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 76,
                  top: 281,
                  width: 460,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '行政区简称(i18n)',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 32,
                  top: 321,
                  width: 58,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 32,
                  top: 391,
                  width: 58,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 536,
                  top: 321,
                  width: 689,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '广东省',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 536,
                  top: 391,
                  width: 689,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '广州市',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 49,
                  top: 348,
                  width: 23,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 2,
                          width: 13,
                          height: 13,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFF777777),
                                width: 1,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 23,
                          top: 0,
                          width: 0,
                          height: 16,
                          child: Text(
                            '',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF333333),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 49,
                  top: 419,
                  width: 23,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 2,
                          width: 13,
                          height: 13,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFF777777),
                                width: 1,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 23,
                          top: 0,
                          width: 0,
                          height: 16,
                          child: Text(
                            '',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF333333),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 218,
                  top: 416,
                  width: 50,
                  height: 21,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '已停用',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0xCCEC808D),
                        height: 2,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 237,
                  top: 345,
                  width: 50,
                  height: 21,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '启用中',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0x57A989C5),
                        height: 2,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 506,
                  top: 137,
                  width: 300,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(2),
                      border: Border(
                        top: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        right: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 6,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 386,
                  top: 137,
                  width: 120,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(2),
                      border: Border(
                        left: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        top: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 106,
                          top: 17.5,
                          width: 8,
                          height: 5,
                          child: CustomPaint(
                            size: Size(8, 5),
                            painter: _Path1Painter(),
                          ),
                        ),
                        Positioned(
                          left: 8,
                          top: 6,
                          width: 90,
                          height: 27,
                          child: Text(
                            '区域代码',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 64.6207,
                  width: 1920,
                  height: 64,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 64,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '您当前所在位置：国家&地区 > 行政区划',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 24,
                  top: 85,
                  width: 24,
                  height: 24,
                  child: Icon(
                    IconData(0xE8E6, fontFamily: 'boldIconFont'),
                    size: 24,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1728,
                  top: 281,
                  width: 170,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 1728,
                  top: 391,
                  width: 170,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1728,
                  top: 321,
                  width: 170,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 65,
                  width: 386,
                  height: 56,
                  child: CustomPaint(
                    size: Size(386, 56),
                    painter: _Path2Painter(),
                  ),
                ),
                Positioned(
                  left: 1475,
                  top: 461,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '0755',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1225,
                  top: 461,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '156440300',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1351,
                  top: 461,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '518000',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1602,
                  top: 461,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '上传文件',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFFA989C5),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 90,
                  top: 461,
                  width: 446,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'shenzhen \n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 32,
                  top: 461,
                  width: 58,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 536,
                  top: 461,
                  width: 689,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '深圳市',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 49,
                  top: 489,
                  width: 23,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 2,
                          width: 13,
                          height: 13,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFF777777),
                                width: 1,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 23,
                          top: 0,
                          width: 0,
                          height: 16,
                          child: Text(
                            '',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF333333),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1728,
                  top: 461,
                  width: 170,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1602,
                  top: 531,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '查看坐标',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFFA989C5),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1475,
                  top: 531,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '0755',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1225,
                  top: 531,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '156440303',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1351,
                  top: 531,
                  width: 126,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '518000',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 90,
                  top: 531,
                  width: 446,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 72,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '福田区\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 32,
                  top: 531,
                  width: 58,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 536,
                  top: 531,
                  width: 689,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Futian district',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 49,
                  top: 558,
                  width: 23,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 2,
                          width: 13,
                          height: 13,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFF777777),
                                width: 1,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 23,
                          top: 0,
                          width: 0,
                          height: 16,
                          child: Text(
                            '',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF333333),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 212,
                  top: 555,
                  width: 50,
                  height: 21,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '启用中',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0x57A989C5),
                        height: 2,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1728,
                  top: 531,
                  width: 170,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 193,
                  top: 486,
                  width: 50,
                  height: 21,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '启用中',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0x57A989C5),
                        height: 2,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 120,
                  top: 419,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEA4F, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 88,
                  top: 348,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEA42, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 120,
                  top: 488,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEA42, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 149,
                  top: 562,
                  width: 8,
                  height: 8,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFF4C5773),
                    ),
                  ),
                ),
                Positioned(
                  left: 1709,
                  top: 370,
                  width: 200,
                  height: 170,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(8),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 15,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '新增下级',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 120,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '删除',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 50,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '编辑',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 85,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '多语言',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 826,
                  top: 147,
                  width: 170,
                  height: 19,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 69,
                          height: 19,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 3,
                                  width: 13,
                                  height: 13,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned.fill(
                                          child: Container(
                                            decoration: BoxDecoration(
                                              shape: BoxShape.circle,
                                              color: Color(0xFFFFFFFF),
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 3,
                                          top: 3,
                                          width: 7,
                                          height: 7,
                                          child: Container(
                                            decoration: BoxDecoration(
                                              shape: BoxShape.circle,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 21,
                                  top: 0,
                                  width: 48,
                                  height: 19,
                                  child: Text(
                                    '启用中',
                                    style: TextStyle(
                                      fontSize: 16,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 101,
                          top: 0,
                          width: 69,
                          height: 19,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 3,
                                  width: 13,
                                  height: 13,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned.fill(
                                          child: Container(
                                            decoration: BoxDecoration(
                                              shape: BoxShape.circle,
                                              color: Color(0xFFFFFFFF),
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 3,
                                          top: 3,
                                          width: 7,
                                          height: 7,
                                          child: Container(
                                            decoration: BoxDecoration(
                                              shape: BoxShape.circle,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 21,
                                  top: 0,
                                  width: 48,
                                  height: 19,
                                  child: Text(
                                    '已停用',
                                    style: TextStyle(
                                      fontSize: 16,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 36,
                  top: 209,
                  width: 80,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF4C5773), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 26,
                          top: 11.5,
                          width: 28,
                          height: 17,
                          child: Text(
                            '启用',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF4C5773),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 537,
                  top: 281,
                  width: 689,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '本地语简称',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(32, 0);
    path.lineTo(32, 587);
    path.lineTo(24.1016, 587);
    path.lineTo(0, 587);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}

class _Path1Painter extends CustomPainter {
  const _Path1Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(8, 0);
    path.lineTo(4, 5);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path1Painter oldDelegate) => false;
}

class _Path2Painter extends CustomPainter {
  const _Path2Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(386, 0);
    path.lineTo(386, 56);
    path.lineTo(0, 56);
    path.lineTo(0, 0);
    path.close();
    canvas.drawPath(path, Paint()..color = Color(0x1AFE4066));
    canvas.drawPath(
      path,
      Paint()
        ..color = Color(0x99FE4066)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1,
    );
  }

  @override
  bool shouldRepaint(_Path2Painter oldDelegate) => false;
}
