name: ruoqi_flutter_ui
description: RuoQi Flutter monorepo.
publish_to: 'none'

environment:
  sdk: ^3.12.0

workspace:
  - apps/platform
  - apps/customer
  - packages/ruoqi_common
  - packages/ruoqi_network

dev_dependencies:
  melos: ^6.3.0
