// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 取消导入 (语言/导入/取消导入)
class Va4OSi31kPage extends StatelessWidget {
  const Va4OSi31kPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 678,
                  top: 155,
                  width: 700,
                  height: 245,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(2),
                      border: Border.all(color: Color(0xFF4C5773), width: 1),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 65,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF7172AD),
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 10,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'XX管理后台',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 208,
                          top: 21,
                          width: 12,
                          height: 12,
                          child: Icon(
                            IconData(0xE8F1, fontFamily: 'lightIconFont'),
                            size: 12,
                            color: Color(0xFF777777),
                          ),
                        ),
                        Positioned(
                          left: 252,
                          top: 0,
                          width: 130,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 17,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE8B2, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFFFFFFFF),
                          ),
                        ),
                        Positioned(
                          left: 1789,
                          top: 11,
                          width: 100,
                          height: 44,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出管理',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 228,
                  top: 65,
                  width: 1692,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 228,
                  top: 384,
                  width: 32,
                  height: 420,
                  child: CustomPaint(
                    size: Size(32, 420),
                    painter: _Path0Painter(),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 145,
                  width: 220,
                  height: 921,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFEFF1F3),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 56,
                          width: 220,
                          height: 185,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4,
                                  top: 4,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 46,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 88,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 130,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 17,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '多语言',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 59,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '翻译',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 101,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '导入',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 143,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '导出',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 220,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '语言',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF949AAB),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 65,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 97,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '基础',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 21,
                        color: Color(0xFF949AAB),
                        fontWeight: FontWeight.w700,
                        height: 0.9524,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 129,
                  width: 220,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 953,
                  top: 170,
                  width: 150,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      'Drop file or',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 922,
                  top: 314,
                  width: 286,
                  height: 30,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      'support formats are  .json, .xliff, .po\nmax size  100M',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.6667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 953,
                  top: 238,
                  width: 150,
                  height: 44,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(2),
                      border: Border.all(color: Color(0xFFA989C5), width: 1),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      'SELECT FILE',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFFA989C5),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1042,
                  top: 446,
                  width: 126,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '翻译数量',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 860,
                  top: 446,
                  width: 182,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '文件名称',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 678,
                  top: 446,
                  width: 182,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '语言',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1042,
                  top: 486,
                  width: 126,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '10',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 860,
                  top: 486,
                  width: 182,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'en.json',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1168,
                  top: 446,
                  width: 210,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '已解决/冲突',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1168,
                  top: 486,
                  width: 210,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '0/0',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 678,
                  top: 486,
                  width: 182,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(2),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFD32F2F), width: 1),
                      ),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 168,
                          top: 42.5,
                          width: 8,
                          height: 5,
                          child: CustomPaint(
                            size: Size(8, 5),
                            painter: _Path1Painter(),
                          ),
                        ),
                        Positioned(
                          left: 8,
                          top: 15,
                          width: 152,
                          height: 60,
                          child: Text(
                            '',
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF949AAB),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 678,
                  top: 576,
                  width: 182,
                  height: 30,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      'Select existing language',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFFD32F2F),
                        height: 1.6667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1173,
                  top: 612,
                  width: 90,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFF2F2F2), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 17,
                          top: 11.5,
                          width: 56,
                          height: 17,
                          child: Text(
                            '取消导入',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFF333333),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1288,
                  top: 612,
                  width: 90,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 31,
                          top: 11.5,
                          width: 28,
                          height: 17,
                          child: Text(
                            '导入',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 14,
                              color: Color(0xFFFFFFFF),
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned.fill(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x4C000000),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 768,
                  top: 372,
                  width: 400,
                  height: 260,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 600,
                          height: 72,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.bottomLeft,
                            padding: EdgeInsets.only(
                              left: 40,
                              right: 32,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '取消导入',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 24,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 40,
                          top: 127,
                          width: 620,
                          height: 20,
                          child: Text(
                            '确定取消导入吗？',
                            style: TextStyle(),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                        Positioned(
                          left: 181,
                          top: 202,
                          width: 90,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFF2F2F2),
                                width: 1,
                              ),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 31,
                                  top: 11.5,
                                  width: 28,
                                  height: 17,
                                  child: Text(
                                    '取消',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF333333),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 296,
                          top: 202,
                          width: 90,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFF4C5773),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 31,
                                  top: 11.5,
                                  width: 28,
                                  height: 17,
                                  child: Text(
                                    '确认',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(32, 0);
    path.lineTo(32, 420);
    path.lineTo(24.1016, 420);
    path.lineTo(0, 420);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}

class _Path1Painter extends CustomPainter {
  const _Path1Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(8, 0);
    path.lineTo(4, 5);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path1Painter oldDelegate) => false;
}
