// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 多因素认证 (个人中心/PC-个人中心(基本信息)/多因素认证)
class DAZ8zIokgWIPage extends StatelessWidget {
  const DAZ8zIokgWIPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1250,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 473,
                  top: 100,
                  width: 1400,
                  height: 1100,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 100,
                  width: 1306,
                  height: 72,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '多因素认证',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 16,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.25,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 188,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '手机号：xxx@outlook.com',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 219,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEB1D, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 283,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '邮箱：+86 139******32',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 314,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xEB65, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 188,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '解除绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1588,
                  top: 220,
                  width: 16,
                  height: 16,
                  child: Image.asset(
                    'assets/images/274bfec0-3d60-11ed-a67d-8d155a89f805.svg',
                    fit: BoxFit.contain,
                    width: 16,
                    height: 16,
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 188,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '修改',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1714,
                  top: 220,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE867, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF000000),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 283,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '解除绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1588,
                  top: 315,
                  width: 16,
                  height: 16,
                  child: Image.asset(
                    'assets/images/274bfec0-3d60-11ed-a67d-8d155a89f805.svg',
                    fit: BoxFit.contain,
                    width: 16,
                    height: 16,
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 283,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '修改',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1714,
                  top: 315,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE867, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF000000),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 666,
                  width: 1306,
                  height: 72,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '第三方账号',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 16,
                        color: Color(0xFF4C5773),
                        height: 1.25,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 753,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Facebook',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 849,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Google',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 753,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '解除绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1710,
                  top: 786,
                  width: 16,
                  height: 16,
                  child: Image.asset(
                    'assets/images/274bfec0-3d60-11ed-a67d-8d155a89f805.svg',
                    fit: BoxFit.contain,
                    width: 16,
                    height: 16,
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 849,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 849,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 786,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE876, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 881,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE881, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1710,
                  top: 881,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE903, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF000000),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 753,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 54,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 54,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'Personal Center',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 1559,
                          top: 20,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE808, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF777777),
                          ),
                        ),
                        Positioned(
                          left: 1799,
                          top: 15,
                          width: 24,
                          height: 24,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(12),
                            child: Image.asset(
                              'assets/images/e342c440-4d0d-11ec-8bda-b1ac5e5c94c9.png',
                              fit: BoxFit.contain,
                              width: 24,
                              height: 24,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 252,
                          top: 0,
                          width: 130,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 1829,
                          top: 17,
                          width: 53,
                          height: 20,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned.fill(
                                  child: Text(
                                    'Nick',
                                    style: TextStyle(),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 38,
                                  top: 7,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE988,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF7F7F7F),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 1593,
                          top: 13,
                          width: 200,
                          height: 30,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned.fill(
                                  child: Container(
                                    decoration: BoxDecoration(
                                      color: Color(0xFFFFFFFF),
                                      borderRadius: BorderRadius.circular(2),
                                      border: Border.all(
                                        color: Color(0xFFD7D7D7),
                                        width: 1,
                                      ),
                                    ),
                                    alignment: Alignment.centerLeft,
                                    padding: EdgeInsets.only(
                                      left: 8,
                                      right: 0,
                                      top: 0,
                                      bottom: 0,
                                    ),
                                    child: Text(
                                      '🇨🇳  中国: china.cn（简体中文）',
                                      textAlign: TextAlign.left,
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: Color(0xFF333333),
                                        height: 1.6667,
                                      ),
                                      overflow: TextOverflow.visible,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 186,
                                  top: 11,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE783,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 1593,
                          top: 14,
                          width: 200,
                          height: 30,
                          child: CustomPaint(
                            size: Size(200, 30),
                            painter: _Path0Painter(),
                          ),
                        ),
                        Positioned(
                          left: 1799,
                          top: 14,
                          width: 94,
                          height: 30,
                          child: CustomPaint(
                            size: Size(94, 30),
                            painter: _Path1Painter(),
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 11,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE7E5, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 168,
                  top: 100,
                  width: 280,
                  height: 215,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 168,
                  top: 259,
                  width: 280,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      'ID：HDEDL007：主账号',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 244,
                  top: 120,
                  width: 128,
                  height: 128,
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(106),
                    child: Image.asset(
                      'assets/images/1c2884f0-290b-11ed-acf8-8195c680d6c1.png',
                      fit: BoxFit.contain,
                      width: 128,
                      height: 128,
                    ),
                  ),
                ),
                Positioned(
                  left: 168,
                  top: 339,
                  width: 280,
                  height: 324,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '基本信息',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 192,
                          width: 280,
                          height: 66,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '账号安全',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 64,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '多因素认证',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 128,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'API秘钥',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 24,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xEB30, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF000000),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 88,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE816, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF000000),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 217,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE7E5, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF000000),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 152,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE84A, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF000000),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 258,
                          width: 280,
                          height: 66,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '本土化',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 283,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xEAAA, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 945,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Wechat',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 1040,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'Github',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 945,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '解除绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1710,
                  top: 977,
                  width: 16,
                  height: 16,
                  child: Image.asset(
                    'assets/images/274bfec0-3d60-11ed-a67d-8d155a89f805.svg',
                    fit: BoxFit.contain,
                    width: 16,
                    height: 16,
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 1040,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 1040,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '绑定',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1710,
                  top: 1072,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE903, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF000000),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 945,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 977,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xED3F, fontFamily: 'lightIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 1072,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xE888, fontFamily: 'boldIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 379,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'OPT 口令验证',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 410,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xED0F, fontFamily: 'lightIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 474,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '人脸识别验证',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 505,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xECEA, fontFamily: 'lightIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 379,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '敬请期待',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 379,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 474,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '敬请期待',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 474,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 570,
                  width: 1062,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '指纹验证',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 18,
                        color: Color(0xFF4C5773),
                        height: 1.1111,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 540,
                  top: 601,
                  width: 16,
                  height: 16,
                  child: Icon(
                    IconData(0xED2B, fontFamily: 'lightIconFont'),
                    size: 16,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1575,
                  top: 570,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '敬请期待',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1697,
                  top: 570,
                  width: 122,
                  height: 80,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFF7F8FA),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 40,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 64,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'Personal Center',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 252,
                          top: 0,
                          width: 130,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 16,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE7E5, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                        Positioned(
                          left: 1807,
                          top: 12,
                          width: 100,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF7A8599),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(200, 0);
    path.lineTo(200, 30);
    path.lineTo(0, 30);
    path.lineTo(0, 0);
    path.close();
    canvas.drawPath(path, Paint()..color = Color(0x1AFE4066));
    canvas.drawPath(
      path,
      Paint()
        ..color = Color(0x99FE4066)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1,
    );
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}

class _Path1Painter extends CustomPainter {
  const _Path1Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(94, 0);
    path.lineTo(94, 30);
    path.lineTo(0, 30);
    path.lineTo(0, 0);
    path.close();
    canvas.drawPath(path, Paint()..color = Color(0x1AFE4066));
    canvas.drawPath(
      path,
      Paint()
        ..color = Color(0x99FE4066)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1,
    );
  }

  @override
  bool shouldRepaint(_Path1Painter oldDelegate) => false;
}
