// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 通用验证(手机号、邮箱) (个人中心/PC-个人中心(基本信息)/通用验证(手机号、邮箱))
class xdLB4kjm1Page extends StatelessWidget {
  const xdLB4kjm1Page({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned.fill(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x4C000000),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 610,
                  top: 527,
                  width: 700,
                  height: 320,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 275,
                          top: 250,
                          width: 150,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFF4C5773),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 54,
                                  top: 11,
                                  width: 42,
                                  height: 17,
                                  child: Text(
                                    '下一步',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 600,
                          height: 72,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.bottomLeft,
                            padding: EdgeInsets.only(
                              left: 40,
                              right: 32,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '验证邮箱：avey777@163.com',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 24,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 648,
                          top: 36,
                          width: 24,
                          height: 24,
                          child: Icon(
                            IconData(0xEA5B, fontFamily: 'boldIconFont'),
                            size: 24,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                        Positioned(
                          left: 36,
                          top: 137,
                          width: 439,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(2),
                              border: Border(
                                left: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                                top: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                                bottom: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 8,
                              right: 6,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '请输入验证码',
                              textAlign: TextAlign.left,
                              style: TextStyle(fontSize: 14),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 475,
                          top: 137,
                          width: 150,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFF949AAB),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(2),
                                bottomLeft: Radius.circular(0),
                                bottomRight: Radius.circular(2),
                              ),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 40,
                                  top: 19.5,
                                  width: 70,
                                  height: 17,
                                  child: Text(
                                    '获取验证码',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 43,
                          top: 87,
                          width: 117,
                          height: 20,
                          child: Text(
                            '切换至 手机号验证',
                            style: TextStyle(color: Color(0xFF4C5773)),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 610,
                  top: 131,
                  width: 700,
                  height: 320,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 275,
                          top: 250,
                          width: 150,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFF4C5773),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 54,
                                  top: 11,
                                  width: 42,
                                  height: 17,
                                  child: Text(
                                    '下一步',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 600,
                          height: 72,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.bottomLeft,
                            padding: EdgeInsets.only(
                              left: 40,
                              right: 32,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '验证手机号：+86 15020579521',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 24,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 648,
                          top: 36,
                          width: 24,
                          height: 24,
                          child: Icon(
                            IconData(0xEA5B, fontFamily: 'boldIconFont'),
                            size: 24,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                        Positioned(
                          left: 36,
                          top: 137,
                          width: 439,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(2),
                              border: Border(
                                left: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                                top: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                                bottom: BorderSide(
                                  color: Color(0xFF797979),
                                  width: 1,
                                ),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 8,
                              right: 6,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '请输入验证码',
                              textAlign: TextAlign.left,
                              style: TextStyle(fontSize: 14),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 475,
                          top: 137,
                          width: 150,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFF949AAB),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(2),
                                bottomLeft: Radius.circular(0),
                                bottomRight: Radius.circular(2),
                              ),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 40,
                                  top: 19.5,
                                  width: 70,
                                  height: 17,
                                  child: Text(
                                    '获取验证码',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 44,
                          top: 85,
                          width: 103,
                          height: 20,
                          child: Text(
                            '切换至 邮箱验证',
                            style: TextStyle(color: Color(0xFF4C5773)),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
