// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// Google登录 (设置/auth登录/Google登录)
class P9m4HsZU3gPage extends StatelessWidget {
  const P9m4HsZU3gPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1278,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 228,
                  top: 65,
                  width: 1692,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 145,
                  width: 220,
                  height: 1118,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFEFF1F3),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 18,
                          width: 220,
                          height: 177,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4,
                                  top: 4,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 46,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 88,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 130,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 17,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '通用',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 59,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '本土化',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 101,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '电子邮件',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 143,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '编码规则',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 185,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '短信',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 227,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    'auth登录',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 269,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '验证消息',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 65,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 97,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '设置',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 21,
                        color: Color(0xFF949AAB),
                        fontWeight: FontWeight.w700,
                        height: 0.9524,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 129,
                  width: 220,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 65,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF7172AD),
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 10,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'XX管理后台',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 230,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '设置',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 17,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE8B2, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFFFFFFFF),
                          ),
                        ),
                        Positioned(
                          left: 1789,
                          top: 11,
                          width: 100,
                          height: 44,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出管理',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 310,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '用户',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 390,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '权限',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 470,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '菜单',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 550,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '基础',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 630,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '语言',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 710,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '日志',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 268,
                  top: 145,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'auth登录  >  GOOGLE登录',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 279,
                  top: 250,
                  width: 432,
                  height: 40,
                  child: Text(
                    '允许拥有现有运营后台账户的用户在当前的用户名和密码的基础上，用与他们的电子邮件地址相匹配的谷歌账户登录。',
                    style: TextStyle(),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 279,
                  top: 198,
                  width: 179,
                  height: 34,
                  child: Text(
                    'Google账号登录',
                    style: TextStyle(fontWeight: FontWeight.w700),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 279,
                  top: 318,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '客户ID',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 288,
                  top: 350,
                  width: 400,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF949AAB), width: 1),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 6,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '{your-client-id}.apps.googleusercontent.com',
                      textAlign: TextAlign.left,
                      style: TextStyle(fontSize: 14),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
                Positioned(
                  left: 279,
                  top: 408,
                  width: 409,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '允许用户登录，如果用户的Google帐户电子邮件地址来自：',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF949AAB),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 288,
                  top: 440,
                  width: 400,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFF949AAB), width: 1),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 6,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      'mycompany.com',
                      textAlign: TextAlign.left,
                      style: TextStyle(fontSize: 14),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
                Positioned(
                  left: 288,
                  top: 517,
                  width: 120,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 20,
                          top: 18.5,
                          width: 80,
                          height: 19,
                          child: Text(
                            '保存并启用',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFFFFFFFF),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 273,
                  top: 152,
                  width: 66,
                  height: 18,
                  child: CustomPaint(
                    size: Size(66, 18),
                    painter: _Path0Painter(),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(66, 0);
    path.lineTo(66, 18);
    path.lineTo(0, 18);
    path.lineTo(0, 0);
    path.close();
    canvas.drawPath(path, Paint()..color = Color(0x1AFE4066));
    canvas.drawPath(
      path,
      Paint()
        ..color = Color(0x99FE4066)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1,
    );
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}
