// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// API秘钥 (个人中心/PC-个人中心(基本信息)/API秘钥)
class rjvZWT5DwPage extends StatelessWidget {
  const rjvZWT5DwPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 168,
                  top: 100,
                  width: 280,
                  height: 215,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 168,
                  top: 259,
                  width: 280,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      'ID：HDEDL007：主账号',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 244,
                  top: 120,
                  width: 128,
                  height: 128,
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(106),
                    child: Image.asset(
                      'assets/images/1c2884f0-290b-11ed-acf8-8195c680d6c1.png',
                      fit: BoxFit.contain,
                      width: 128,
                      height: 128,
                    ),
                  ),
                ),
                Positioned(
                  left: 168,
                  top: 339,
                  width: 280,
                  height: 325,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '基本信息',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 192,
                          width: 280,
                          height: 66,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '账号安全',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 64,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '多因素认证',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 128,
                          width: 280,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'API秘钥',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 24,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xEB30, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 88,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE816, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 217,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE7E5, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 152,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xE84A, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 258,
                          width: 280,
                          height: 66,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(0),
                                topRight: Radius.circular(0),
                                bottomLeft: Radius.circular(4),
                                bottomRight: Radius.circular(4),
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '本土化',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFF4C5773),
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 13,
                          top: 283,
                          width: 16,
                          height: 16,
                          child: Icon(
                            IconData(0xEAAA, fontFamily: 'boldIconFont'),
                            size: 16,
                            color: Color(0xFF949AAB),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 100,
                  width: 1306,
                  height: 72,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 24,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '您的 API 秘钥 ',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 24,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.8333,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 207,
                  width: 1306,
                  height: 120,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 20,
                      top: 20,
                      bottom: 20,
                    ),
                    child: Text(
                      'Application ID\n这是你唯一的应用身份验证，当你使用 API 的时候使用它进行验证。',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF5A5E9A),
                        height: 2.2857,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 343,
                  width: 1306,
                  height: 120,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border(
                        left: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        top: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        right: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 20,
                      top: 20,
                      bottom: 20,
                    ),
                    child: Text(
                      'Search API Key\n这是可以安全使用的公共API秘钥。此秘钥仅支持数据查询。',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF5A5E9A),
                        height: 2.2857,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 463,
                  width: 1306,
                  height: 120,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border(
                        left: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        right: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 20,
                      top: 20,
                      bottom: 20,
                    ),
                    child: Text(
                      'Write API Key\n这是 一个私有的API秘钥。请保密并仅在后端使用它：此秘钥用于创建、更新和删除您的数据。你不能使用它来管理您的其它API秘钥',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF5A5E9A),
                        height: 2.2857,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 513,
                  top: 599,
                  width: 1306,
                  height: 120,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(4),
                      border: Border(
                        left: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        right: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                        bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 20,
                      top: 20,
                      bottom: 20,
                    ),
                    child: Text(
                      'Admin API Key\n这是 ADMIN API 秘钥。请保密并仅在后端使用它：此秘钥用于创建、更新和删除您的数据。你还可以使用它来管理您的其它API秘钥。\n此秘钥只对应用所有者开放。',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF5A5E9A),
                        height: 1.7143,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1758,
                  top: 391,
                  width: 24,
                  height: 24,
                  child: Icon(
                    IconData(0xE777, fontFamily: 'boldIconFont'),
                    size: 24,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1758,
                  top: 511,
                  width: 24,
                  height: 24,
                  child: Icon(
                    IconData(0xE777, fontFamily: 'boldIconFont'),
                    size: 24,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1758,
                  top: 647,
                  width: 24,
                  height: 24,
                  child: Icon(
                    IconData(0xE777, fontFamily: 'boldIconFont'),
                    size: 24,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1496,
                  top: 393,
                  width: 241,
                  height: 22,
                  child: Text(
                    '7684d2f2530e999c79e7fa4e12012247',
                    style: TextStyle(),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 1496,
                  top: 513,
                  width: 253,
                  height: 22,
                  child: Text(
                    '·································································',
                    style: TextStyle(fontWeight: FontWeight.w700),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 1496,
                  top: 648,
                  width: 253,
                  height: 22,
                  child: Text(
                    '·································································',
                    style: TextStyle(fontWeight: FontWeight.w700),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 1649,
                  top: 264,
                  width: 88,
                  height: 22,
                  child: Text(
                    '62MLEBY33X\n',
                    style: TextStyle(),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 1758,
                  top: 263,
                  width: 24,
                  height: 24,
                  child: Icon(
                    IconData(0xE777, fontFamily: 'boldIconFont'),
                    size: 24,
                    color: Color(0xFF4C5773),
                  ),
                ),
                Positioned(
                  left: 1734,
                  top: 116,
                  width: 85,
                  height: 20,
                  child: Text(
                    '管理所有秘钥',
                    style: TextStyle(),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 64,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 64,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 32,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'Personal Center',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 252,
                          top: 0,
                          width: 130,
                          height: 56,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 16,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE7E5, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                        Positioned(
                          left: 1807,
                          top: 12,
                          width: 100,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF7A8599),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
