// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 取消绑定 (个人中心/PC-个人中心(基本信息)/多因素认证/取消绑定)
class P9U6oXpOcFPage extends StatelessWidget {
  const P9U6oXpOcFPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned.fill(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x4C000000),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 610,
                  top: 390,
                  width: 700,
                  height: 300,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 572,
                          top: 228,
                          width: 100,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFED6E6E),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 43,
                                  top: 11.5,
                                  width: 14,
                                  height: 17,
                                  child: Text(
                                    '是',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFFFFFFFF),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 600,
                          height: 72,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.bottomLeft,
                            padding: EdgeInsets.only(
                              left: 40,
                              right: 32,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '取消绑定？',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 24,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 648,
                          top: 36,
                          width: 24,
                          height: 24,
                          child: Icon(
                            IconData(0xEA5B, fontFamily: 'boldIconFont'),
                            size: 24,
                            color: Color(0xFF4C5773),
                          ),
                        ),
                        Positioned(
                          left: 40,
                          top: 127,
                          width: 620,
                          height: 20,
                          child: Text(
                            '确定解除绑定吗？ 取消绑定后，不能使用该方式登录。此操作不可逆。',
                            style: TextStyle(),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                        Positioned(
                          left: 457,
                          top: 228,
                          width: 90,
                          height: 40,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Color(0xFFFFFFFF),
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFF2F2F2),
                                width: 1,
                              ),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 38,
                                  top: 11.5,
                                  width: 14,
                                  height: 17,
                                  child: Text(
                                    '否',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF333333),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
