// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 角色 (用户/角色)
class c11sjQSJ1Page extends StatelessWidget {
  const c11sjQSJ1Page({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1920,
      height: 1080,
      child: Stack(
        children: [
          Positioned.fill(
            child: Stack(
              children: [
                Positioned(
                  left: 881,
                  top: 384,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 228,
                  top: 65,
                  width: 1692,
                  height: 90,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 244,
                  top: 820,
                  width: 1652,
                  height: 1,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        top: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 837,
                  width: 676,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 254,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '1',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 302,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '2',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 350,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '3',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 48,
                          top: 0,
                          width: 150,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 136,
                                  top: 13.5,
                                  width: 8,
                                  height: 5,
                                  child: CustomPaint(
                                    size: Size(8, 5),
                                    painter: _Path0Painter(),
                                  ),
                                ),
                                Positioned(
                                  left: 8,
                                  top: 5.5,
                                  width: 120,
                                  height: 21,
                                  child: Text(
                                    '10条/页',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '共N条',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 206,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned.fill(
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(2),
                                    ),
                                    alignment: Alignment.center,
                                  ),
                                ),
                                Positioned(
                                  left: 8,
                                  top: 12,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE9A0,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                                Positioned(
                                  left: 24,
                                  top: 12,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE989,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 494,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned.fill(
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(2),
                                    ),
                                    alignment: Alignment.center,
                                  ),
                                ),
                                Positioned(
                                  left: 6,
                                  top: 12,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE994,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                                Positioned(
                                  left: 22,
                                  top: 12,
                                  width: 8,
                                  height: 8,
                                  child: Icon(
                                    IconData(
                                      0xE9A1,
                                      fontFamily: 'boldIconFont',
                                    ),
                                    size: 8,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 542,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '前往',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 588,
                          top: 2,
                          width: 40,
                          height: 30,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '1',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                              ),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 636,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '页',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 398,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '···',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 12,
                                color: Color(0xFF4C5773),
                                height: 1.6667,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 446,
                          top: 0,
                          width: 40,
                          height: 32,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '10',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 384,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 344,
                  width: 150,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 228,
                  top: 384,
                  width: 32,
                  height: 420,
                  child: CustomPaint(
                    size: Size(32, 420),
                    painter: _Path1Painter(),
                  ),
                ),
                Positioned(
                  left: 248,
                  top: 344,
                  width: 40,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned.fill(
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border(
                                bottom: BorderSide(
                                  color: Color(0xFFF2F2F2),
                                  width: 1,
                                ),
                              ),
                            ),
                            alignment: Alignment.center,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 454,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 384,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '1',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 344,
                  width: 281,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '成员',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 454,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '100',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 344,
                  width: 865,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '备注',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 454,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 384,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '管理员\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 454,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '所有用户',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 145,
                  width: 220,
                  height: 921,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFEFF1F3),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Color(0xFFD7D7D7), width: 1),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 18,
                          width: 220,
                          height: 108,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4,
                                  top: 4,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 4,
                                  top: 46,
                                  width: 212,
                                  height: 42,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 17,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '用户',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                                Positioned(
                                  left: 20,
                                  top: 59,
                                  width: 188,
                                  height: 17,
                                  child: Text(
                                    '角色',
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF4C5773),
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 65,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 97,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '用户',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 21,
                        color: Color(0xFF949AAB),
                        fontWeight: FontWeight.w700,
                        height: 0.9524,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 8,
                  top: 129,
                  width: 220,
                  height: 16,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 259,
                  top: 270,
                  width: 300,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Stack(
                      children: [
                        Positioned.fill(
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 8,
                              right: 6,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '角色名称',
                              textAlign: TextAlign.left,
                              style: TextStyle(fontSize: 14),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 264,
                          top: 11,
                          width: 18,
                          height: 18,
                          child: Icon(
                            IconData(0xE8FF, fontFamily: 'lightIconFont'),
                            size: 18,
                            color: Color(0xFFAAAAAA),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 288,
                  top: 344,
                  width: 314,
                  height: 40,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                      border: Border(
                        bottom: BorderSide(color: Color(0xFFF2F2F2), width: 1),
                      ),
                    ),
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '名称',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 384,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 454,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0x80EFF1F3),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 398,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFFED6E6E),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '管',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 468,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFFA989C5),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '所',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1701,
                  top: 145,
                  width: 120,
                  height: 56,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF4C5773),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 20,
                          top: 18.5,
                          width: 80,
                          height: 19,
                          child: Text(
                            '创建角色组',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Color(0xFFFFFFFF),
                              fontWeight: FontWeight.w700,
                            ),
                            overflow: TextOverflow.visible,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 524,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 524,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '0',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 524,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 524,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '实施经理',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 524,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 538,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFF025478),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '实',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 594,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 594,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '1',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 594,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 594,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '实施专员\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 594,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 608,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFF025478),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '实',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 664,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 664,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '1',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 664,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 664,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '运营经理\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 664,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 678,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFF025478),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '运',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1746,
                  top: 734,
                  width: 150,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '...',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 28,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.5,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 600,
                  top: 734,
                  width: 281,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '1',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        color: Color(0xFF4C5773),
                        height: 1.1667,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 881,
                  top: 734,
                  width: 865,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.center,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 302,
                  top: 734,
                  width: 300,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 20,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '运营专员\n',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 14,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 1.4286,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 734,
                  width: 42,
                  height: 70,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 56,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                  ),
                ),
                Positioned(
                  left: 260,
                  top: 748,
                  width: 42,
                  height: 42,
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Color(0xFF025478),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '运',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 22,
                        color: Color(0xFFFFFFFF),
                        height: 0.9091,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 1646,
                  top: 575,
                  width: 200,
                  height: 150,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFFFFFFFF),
                      borderRadius: BorderRadius.circular(8),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 15,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '编辑名称',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 50,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '设置权限',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFF4C5773),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 85,
                          width: 200,
                          height: 35,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                              border: Border.all(
                                color: Color(0xFFFFFFFF),
                                width: 4,
                              ),
                            ),
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.only(
                              left: 20,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              '删除角色组',
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFFEC808D),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 259,
                  top: 194,
                  width: 655,
                  height: 40,
                  child: Text(
                    '你可以使用组来控制你的用户对你的数据的访问。把用户放在组里，然后到权限部分去控制每个组的访问。管理员和所有用户组是特殊的默认组，不能被删除。',
                    style: TextStyle(),
                    overflow: TextOverflow.visible,
                  ),
                ),
                Positioned(
                  left: 244,
                  top: 145,
                  width: 220,
                  height: 32,
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    alignment: Alignment.centerLeft,
                    padding: EdgeInsets.only(
                      left: 8,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    ),
                    child: Text(
                      '角色',
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        fontSize: 21,
                        color: Color(0xFF4C5773),
                        fontWeight: FontWeight.w700,
                        height: 0.9524,
                      ),
                      overflow: TextOverflow.visible,
                    ),
                  ),
                ),
                Positioned(
                  left: 0,
                  top: 0,
                  width: 1920,
                  height: 65,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Color(0xFF7172AD),
                      borderRadius: BorderRadius.circular(0),
                      boxShadow: [
                        BoxShadow(
                          color: Color(0x26000000),
                          blurRadius: 6,
                          offset: Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          width: 190,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            padding: EdgeInsets.only(
                              left: 10,
                              right: 0,
                              top: 0,
                              bottom: 0,
                            ),
                            child: Text(
                              'XX管理后台',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 230,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '设置',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 17,
                          width: 32,
                          height: 32,
                          child: Icon(
                            IconData(0xE8B2, fontFamily: 'boldIconFont'),
                            size: 32,
                            color: Color(0xFFFFFFFF),
                          ),
                        ),
                        Positioned(
                          left: 1789,
                          top: 11,
                          width: 100,
                          height: 44,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(
                                color: Color(0xFFD7D7D7),
                                width: 1,
                              ),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '退出管理',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 16,
                                color: Color(0xFFFFFFFF),
                                fontWeight: FontWeight.w700,
                                height: 1.25,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 310,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '用户',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 390,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '权限',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 470,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '菜单',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 550,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '基础',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 630,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '语言',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                        Positioned(
                          left: 710,
                          top: 0,
                          width: 80,
                          height: 65,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              '日志',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                fontSize: 14,
                                color: Color(0xA1FFFFFF),
                                height: 1.4286,
                              ),
                              overflow: TextOverflow.visible,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Path0Painter extends CustomPainter {
  const _Path0Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(8, 0);
    path.lineTo(4, 5);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path0Painter oldDelegate) => false;
}

class _Path1Painter extends CustomPainter {
  const _Path1Painter();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    path.moveTo(0, 0);
    path.lineTo(32, 0);
    path.lineTo(32, 420);
    path.lineTo(24.1016, 420);
    path.lineTo(0, 420);
    path.lineTo(0, 0);
    path.close();
  }

  @override
  bool shouldRepaint(_Path1Painter oldDelegate) => false;
}
